// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ7cZNM9jxUJHwuS4EBJTMRud8Tg-QFAk',
    appId: '1:271312927922:web:9186bfc30628c565fd5dab',
    messagingSenderId: '271312927922',
    projectId: 'futvarzea-3702c',
    authDomain: 'futvarzea-3702c.firebaseapp.com',
    storageBucket: 'futvarzea-3702c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdxxdrYjOXLDjSSfqw7oCZ_scpc1w0eKs',
    appId: '1:271312927922:android:be223f092b290c4efd5dab',
    messagingSenderId: '271312927922',
    projectId: 'futvarzea-3702c',
    storageBucket: 'futvarzea-3702c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIqorK9ZubiMbnucvAv-73CpioZI9YXk0',
    appId: '1:271312927922:ios:9f3116f3f7e99315fd5dab',
    messagingSenderId: '271312927922',
    projectId: 'futvarzea-3702c',
    storageBucket: 'futvarzea-3702c.firebasestorage.app',
    iosBundleId: 'com.example.appfute',
  );
}
